<?php

/**
 * BaseapPhysicalUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $first_name
 * @property string $last_name
 * @property timestamp $birth_date
 * @property string $birth_place
 * @property string $address
 * @property string $city
 * @property string $province
 * @property string $zip
 * @property string $status
 * @property string $document_type
 * @property string $document
 * @property integer $simple_network_id
 * @property apSimpleNetwork $apSimpleNetwork
 * 
 * @method string          getFirstName()         Returns the current record's "first_name" value
 * @method string          getLastName()          Returns the current record's "last_name" value
 * @method timestamp       getBirthDate()         Returns the current record's "birth_date" value
 * @method string          getBirthPlace()        Returns the current record's "birth_place" value
 * @method string          getAddress()           Returns the current record's "address" value
 * @method string          getCity()              Returns the current record's "city" value
 * @method string          getProvince()          Returns the current record's "province" value
 * @method string          getZip()               Returns the current record's "zip" value
 * @method string          getStatus()            Returns the current record's "status" value
 * @method string          getDocumentType()      Returns the current record's "document_type" value
 * @method string          getDocument()          Returns the current record's "document" value
 * @method integer         getSimpleNetworkId()   Returns the current record's "simple_network_id" value
 * @method apSimpleNetwork getApSimpleNetwork()   Returns the current record's "apSimpleNetwork" value
 * @method apPhysicalUser  setFirstName()         Sets the current record's "first_name" value
 * @method apPhysicalUser  setLastName()          Sets the current record's "last_name" value
 * @method apPhysicalUser  setBirthDate()         Sets the current record's "birth_date" value
 * @method apPhysicalUser  setBirthPlace()        Sets the current record's "birth_place" value
 * @method apPhysicalUser  setAddress()           Sets the current record's "address" value
 * @method apPhysicalUser  setCity()              Sets the current record's "city" value
 * @method apPhysicalUser  setProvince()          Sets the current record's "province" value
 * @method apPhysicalUser  setZip()               Sets the current record's "zip" value
 * @method apPhysicalUser  setStatus()            Sets the current record's "status" value
 * @method apPhysicalUser  setDocumentType()      Sets the current record's "document_type" value
 * @method apPhysicalUser  setDocument()          Sets the current record's "document" value
 * @method apPhysicalUser  setSimpleNetworkId()   Sets the current record's "simple_network_id" value
 * @method apPhysicalUser  setApSimpleNetwork()   Sets the current record's "apSimpleNetwork" value
 * 
 * @package    authpuppy
 * @subpackage model
 * @author     Frédéric Sheedy
 * @version    SVN: $Id: Builder.php 7380 2010-03-15 21:07:50Z jwage $
 */
abstract class BaseapPhysicalUser extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('apPhysicalUser');
        $this->hasColumn('first_name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('last_name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('birth_date', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('birth_place', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('address', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('city', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('province', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('zip', 'string', 50, array(
             'type' => 'string',
             'length' => '50',
             ));
        $this->hasColumn('user_status', 'string', 50, array(
             'type' => 'string',
             'length' => '50',
             ));
        $this->hasColumn('document_type', 'string', 50, array(
             'type' => 'string',
             'length' => '50',
             ));
        $this->hasColumn('document', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('simple_network_id', 'integer', null, array(
             'type' => 'integer',
             ));


        $this->index('name_idx', array(
             'fields' => 
             array(
              0 => 'name',
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('apSimpleNetwork', array(
             'local' => 'simple_network_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}