<?php

/**
 * BaseapNetworkUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $simple_network_id
 * @property sfGuardUser $User
 * @property apSimpleNetwork $SimpleNetwork
 * 
 * @method integer         getUserId()            Returns the current record's "user_id" value
 * @method integer         getSimpleNetworkId()   Returns the current record's "simple_network_id" value
 * @method sfGuardUser     getUser()              Returns the current record's "User" value
 * @method apSimpleNetwork getSimpleNetwork()     Returns the current record's "SimpleNetwork" value
 * @method apNetworkUser   setUserId()            Sets the current record's "user_id" value
 * @method apNetworkUser   setSimpleNetworkId()   Sets the current record's "simple_network_id" value
 * @method apNetworkUser   setUser()              Sets the current record's "User" value
 * @method apNetworkUser   setSimpleNetwork()     Sets the current record's "SimpleNetwork" value
 * 
 * @package    authpuppy
 * @subpackage model
 * @author     Frédéric Sheedy
 * @version    SVN: $Id: Builder.php 7380 2010-03-15 21:07:50Z jwage $
 */
abstract class BaseapNetworkUser extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ap_network_user');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('simple_network_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('apSimpleNetwork as SimpleNetwork', array(
             'local' => 'simple_network_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}