<?php

/**
 * BaseapSimpleNetwork
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $address
 * @property string $owner
 * @property string $email
 * @property Doctrine_Collection $apNetworkUser
 * 
 * @method string              getName()          Returns the current record's "name" value
 * @method string              getAddress()       Returns the current record's "address" value
 * @method string              getOwner()         Returns the current record's "owner" value
 * @method string              getEmail()         Returns the current record's "email" value
 * @method Doctrine_Collection getApNetworkUser() Returns the current record's "apNetworkUser" collection
 * @method apSimpleNetwork     setName()          Sets the current record's "name" value
 * @method apSimpleNetwork     setAddress()       Sets the current record's "address" value
 * @method apSimpleNetwork     setOwner()         Sets the current record's "owner" value
 * @method apSimpleNetwork     setEmail()         Sets the current record's "email" value
 * @method apSimpleNetwork     setApNetworkUser() Sets the current record's "apNetworkUser" collection
 * 
 * @package    authpuppy
 * @subpackage model
 * @author     Frédéric Sheedy
 * @version    SVN: $Id: Builder.php 7380 2010-03-15 21:07:50Z jwage $
 */
abstract class BaseapSimpleNetwork extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ap_simple_network');
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '50',
             ));
        $this->hasColumn('address', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('owner', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('network_logo', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));


        $this->index('name_idx', array(
             'fields' => 
             array(
              0 => 'name',
             ),
             'type' => 'unique',
             ));
        $this->option('symfony', array(
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('sfGuardUser as Users', array(
             'refClass' => 'apNetworkUser',
             'local' => 'simple_network_id',
             'foreign' => 'user_id'));

        $this->hasMany('apNetworkUser', array(
             'local' => 'id',
             'foreign' => 'simple_network_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}