<?php

// +------------------------------------------------------------------------+
// | AuthPuppy Authentication Server                                        |
// | =============================                                          |
// |                                                                        |
// | AuthPuppy is the new generation of authentication server for           |
// | a wifidog based captive portal suite                                   |
// +------------------------------------------------------------------------+
// | PHP version 5 required.                                                |
// +------------------------------------------------------------------------+
// | Homepage:     http://www.authpuppy.org/                                |
// | Launchpad:    http://www.launchpad.net/authpuppy                       |
// +------------------------------------------------------------------------+
// | This program is free software; you can redistribute it and/or modify   |
// | it under the terms of the GNU General Public License as published by   |
// | the Free Software Foundation; either version 2 of the License, or      |
// | (at your option) any later version.                                    |
// |                                                                        |
// | This program is distributed in the hope that it will be useful,        |
// | but WITHOUT ANY WARRANTY; without even the implied warranty of         |
// | MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the          |
// | GNU General Public License for more details.                           |
// |                                                                        |
// | You should have received a copy of the GNU General Public License along|
// | with this program; if not, write to the Free Software Foundation, Inc.,|
// | 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.            |
// +------------------------------------------------------------------------+


/**
 * PluginapApplicablePoliciesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    apConnectionPoliciesPlugin
 * @author     Geneviève Bastien <gbastien@versatic.net>
 * @copyright  2010
 * @version    $Version: 0.1.2$
 */
class PluginapApplicablePoliciesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginapApplicablePoliciesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginapApplicablePolicies');
    }
    
    public function getForIdentity($identity) {
      // Return only if the connection was today, otherwise, there is no application policies
      $lastconn = Doctrine::getTable('Connection')->getLastConnectionFor($identity, true);
      if ($lastconn) {
        $policies = $lastconn->getPolicies();
        foreach ($policies as $policy) {
          $policy->setThisTotalData($policy->getThisTotalData() - ($lastconn->getIncoming() + $lastconn->getOutgoing()));
        }
        return $policies;
         
      }
      else return array();
    }
    
    
}