<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SimpleNetworkUser extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('ap_network_user', array(
             'user_id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 8,
             ),
             'simple_network_id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 8,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'user_id',
              1 => 'simple_network_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('ap_network_user');
    }
}