<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NetworkNodeField extends apPluginDoctrineMigrationBase
{
  public function up()
  {
    $this->addColumn('nodes', 'simple_network_id', 'integer', 8, array(
          'length' => 8
             ));
  }

  public function down()
  {
    $this->removeColumn('nodes', 'simple_network_id');
  }
  
  public function getScripts() {
    return array("INSERT INTO sf_guard_permission (name,description,created_at,updated_at) values('network_manager','permission to administer a given network','".date('Y-m-d')."','".date('Y-m-d')."')"); 
  }
}