<?php

/**
 * PluginapPhysicalUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginapPhysicalUserTable extends Doctrine_Table
{
    static public $document_types = array(
      "identity card" => "Identity card",
      "passport" => "Passport",
      "driving license" => "Driving license",
      "other" => "Other",
    );
    /**
     * Returns an instance of this class.
     *
     * @return object PluginapPhysicalUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginapPhysicalUser');
    }
    
    public function getDocumentTypes()
    {
      return self::$document_types;
    }
}