<?php

/**
 * PluginapUserRememberMeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginapUserRememberMeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginapUserRememberMeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginapUserRememberMe');
    }
    
    protected function getUserWithCookie($cookievalue) {
      $q = $this->createQuery('r')
        ->where('remember_me_cookie = ?', strtolower($cookievalue));
      return $q->fetchOne();
    }
    
    public function findUser() {
      $cookievalue = sfContext::getInstance()->getRequest()->getCookie('localUserCookie');
      if (!is_null($cookievalue)) {
        return $this->getUserWithCookie($cookievalue);
      } 
      return null;
  }
}