<?php

/**
 * PluginapUserRememberMe
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7380 2010-03-15 21:07:50Z jwage $
 */
abstract class PluginapUserRememberMe extends BaseapUserRememberMe
{  
  public function save(Doctrine_Connection $conn = null) {
    // Set the cookie
    if ($this->isNew() ) {
      $cookievalue = apUtils::generateNonce();
      sfContext::getInstance()->getResponse()->setCookie('localUserCookie', $cookievalue);   
      $this->setRememberMeCookie($cookievalue);
    }
    return parent::save($conn);
  }
  
  public function getUser() {
    return $this->getApUser();
  }
  
  public function delete(Doctrine_Connection $conn = null)
  {
    sfContext::getInstance()->getResponse()->setCookie('localUserCookie', null);
    parent::delete($conn);
  }

}