<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class physicalUserTable extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('apPhysicalUser', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'first_name' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 255,
             ),
             'last_name' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 255,
             ),
             'birth_date' => 
             array(
              'type' => 'timestamp',
              'length' => 25,
             ),
             'birth_place' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'document' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'simple_network_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('apPhysicalUser');
    }
}