<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class apUserFields extends Doctrine_Migration_Base
{
  public function up()
  {
    $this->addColumn('ap_user', 'physical_user_id', 'integer', 8, array(
          'length' => 8
             ));
  }

  public function down()
  {
    $this->removeColumn('ap_user', 'physical_user_id');
  }
  
 
}