<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class apUserNotesPayment extends Doctrine_Migration_Base
{
  public function up()
  {
    $this->addColumn('ap_user', 'payment', 'string', 100, array(
          'length' => 100
             ));
    $this->addColumn('ap_user', 'ticket_notes', 'string', 500, array(
          'length' => 500
             ));
  }

  public function down()
  {
    $this->removeColumn('ap_user', 'payment');
    $this->removeColumn('ap_user', 'ticket_notes');
  }
  
 
}