<?php

/**
 * PluginapNetworkUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginapNetworkUserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginapNetworkUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginapNetworkUser');
    }
}