<?php

/**
 * PluginapSimpleNetworkTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginapSimpleNetworkTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginapSimpleNetworkTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginapSimpleNetwork');
    }
}